rover1:
  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: [ "joint_front_left", "joint_rear_left" ]
    right_wheel: [ "joint_front_right", "joint_rear_right" ]
    publish_rate: 50
    cmd_vel_timeout: 0.5
    base_frame_id: "base_link"
    wheel_separation: 0.8
    wheel_radius: 0.1
    enable_odom_tf: true

rover2:
  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: [ "joint_front_left", "joint_rear_left" ]
    right_wheel: [ "joint_front_right", "joint_rear_right" ]
    publish_rate: 50
    cmd_vel_timeout: 0.5
    base_frame_id: "base_link"
    wheel_separation: 0.8
    wheel_radius: 0.1
    enable_odom_tf: true
